bili_dynamic:     #下面的设置暂不可用，请暂时不要修改
  enable: True    #是否开启动态推送功能
  dynamic_interval: 30 #动态检查间隔时间，单位为秒
  is_only_master: false #是否仅允许master订阅
  is_QQ_chek: false #是否检测qq小程序里的视频链接

网易云卡片:    #绘制网易云歌曲分享卡片
  enable: false
  解析自带音频下载url: false #涉及付费音乐版权问题，只能以文件形式发送了,不允许进行传播、销售等商业活动!!
网易云解析:
  enable_proxy: False  #使用common_config/basic_config中填写的代理。
  wyy_prase_url: 'http://nas.manshuo.ink:5000/wyy'      #网易云解析用url，原url已被废弃，请参考https://github.com/Suxiaoqinx/Netease_url
流媒体:
  youtube:
    download_audio_level: 0  #下载音频所需权限等级
    download_video_level: 4  #下载视频所需权限等级
  asmr:
    download_audio_level: 4  #下载音频所需权限等级
